In [2]:
!pip install numpy

In [4]:
import numpy as np

In [10]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2,))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

data

array([[[0.63073836, 0.73568876, 0.2236113 , 0.51724737],
        [0.48788192, 0.85654494, 0.06496224, 0.71598971],
        [0.09321683, 0.48017284, 0.93660609, 0.70916962]],

       [[0.59490722, 0.59765232, 0.27610321, 0.41815835],
        [0.94809409, 0.24160136, 0.65200922, 0.25020372],
        [0.99398069, 0.14750155, 0.09718533, 0.82909488]]])

In [12]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [14]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [16]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [35]:
arr = np.array([[1,2,3,4,],[1,2,3,4]])
type(arr)

numpy.ndarray

In [37]:
#Attributes
shape = data.shape
size = data.size
types = data.dtype

In [39]:
shape

(2, 3, 4)

In [41]:
size

24

In [43]:
types

dtype('float64')

In [45]:
#Sclicing 
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
singlevel = data[0][0][0]

In [47]:
arr

array([[0.63073836, 0.73568876, 0.2236113 , 0.51724737],
       [0.48788192, 0.85654494, 0.06496224, 0.71598971],
       [0.09321683, 0.48017284, 0.93660609, 0.70916962]])

In [49]:
slicer

array([[[0.63073836, 0.73568876, 0.2236113 , 0.51724737],
        [0.48788192, 0.85654494, 0.06496224, 0.71598971],
        [0.09321683, 0.48017284, 0.93660609, 0.70916962]],

       [[0.59490722, 0.59765232, 0.27610321, 0.41815835],
        [0.94809409, 0.24160136, 0.65200922, 0.25020372],
        [0.99398069, 0.14750155, 0.09718533, 0.82909488]]])

In [51]:
reverse

array([[0.59490722, 0.59765232, 0.27610321, 0.41815835],
       [0.94809409, 0.24160136, 0.65200922, 0.25020372],
       [0.99398069, 0.14750155, 0.09718533, 0.82909488]])

In [53]:
singlevel

0.6307383554275978

In [55]:
data

array([[[0.63073836, 0.73568876, 0.2236113 , 0.51724737],
        [0.48788192, 0.85654494, 0.06496224, 0.71598971],
        [0.09321683, 0.48017284, 0.93660609, 0.70916962]],

       [[0.59490722, 0.59765232, 0.27610321, 0.41815835],
        [0.94809409, 0.24160136, 0.65200922, 0.25020372],
        [0.99398069, 0.14750155, 0.09718533, 0.82909488]]])

In [57]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [59]:
list1

array([0.54496957, 0.10951829, 0.07885906, 0.76572763, 0.46349287,
       0.34437118, 0.37501879, 0.96250348, 0.58642859, 0.84951697])

In [61]:
list2

array([0.02946455, 0.238268  , 0.18089664, 0.53571205, 0.88206224,
       0.2306156 , 0.69830561, 0.32109008, 0.10615402, 0.78883775])

In [63]:
#Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [65]:
add

array([0.57443412, 0.34778629, 0.25975569, 1.30143968, 1.34555511,
       0.57498678, 1.0733244 , 1.28359356, 0.69258261, 1.63835472])

In [67]:
sub

array([ 0.51550502, -0.1287497 , -0.10203758,  0.23001558, -0.41856937,
        0.11375558, -0.32328683,  0.6414134 ,  0.48027456,  0.06067922])

In [69]:
div

array([18.49577198,  0.45964332,  0.43593434,  1.4293642 ,  0.52546504,
        1.49326923,  0.53704106,  2.99761201,  5.52431806,  1.0769223 ])

In [71]:
mult

array([0.01605728, 0.0260947 , 0.01426534, 0.41020952, 0.40882956,
       0.07941737, 0.26187772, 0.30905032, 0.06225175, 0.67013106])

In [73]:
dot

2.258184623758159

In [75]:
#Stat functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [77]:
sqrt

5.0

In [79]:
ab

2

In [81]:
power

128

In [83]:
log

3.2188758248682006

In [85]:
exp

array([ 7.3890561 , 20.08553692])

In [87]:
mins

0.07885905609261679

In [89]:
maxs

0.962503481143538

In [91]:
data

array([[[0.63073836, 0.73568876, 0.2236113 , 0.51724737],
        [0.48788192, 0.85654494, 0.06496224, 0.71598971],
        [0.09321683, 0.48017284, 0.93660609, 0.70916962]],

       [[0.59490722, 0.59765232, 0.27610321, 0.41815835],
        [0.94809409, 0.24160136, 0.65200922, 0.25020372],
        [0.99398069, 0.14750155, 0.09718533, 0.82909488]]])

In [93]:
data[0][0][0] = 700

In [95]:
data

array([[[7.00000000e+02, 7.35688761e-01, 2.23611301e-01, 5.17247373e-01],
        [4.87881921e-01, 8.56544943e-01, 6.49622403e-02, 7.15989715e-01],
        [9.32168313e-02, 4.80172839e-01, 9.36606087e-01, 7.09169621e-01]],

       [[5.94907217e-01, 5.97652318e-01, 2.76103207e-01, 4.18158355e-01],
        [9.48094092e-01, 2.41601355e-01, 6.52009224e-01, 2.50203718e-01],
        [9.93980686e-01, 1.47501547e-01, 9.71853339e-02, 8.29094885e-01]]])

In [97]:
data.sort()
data

array([[[2.23611301e-01, 5.17247373e-01, 7.35688761e-01, 7.00000000e+02],
        [6.49622403e-02, 4.87881921e-01, 7.15989715e-01, 8.56544943e-01],
        [9.32168313e-02, 4.80172839e-01, 7.09169621e-01, 9.36606087e-01]],

       [[2.76103207e-01, 4.18158355e-01, 5.94907217e-01, 5.97652318e-01],
        [2.41601355e-01, 2.50203718e-01, 6.52009224e-01, 9.48094092e-01],
        [9.71853339e-02, 1.47501547e-01, 8.29094885e-01, 9.93980686e-01]]])

In [99]:
print(data.shape)

(2, 3, 4)


In [101]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [105]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [107]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [109]:
data

array([[[2.23611301e-01, 5.17247373e-01, 7.35688761e-01, 7.00000000e+02,
         6.49622403e-02, 4.87881921e-01],
        [7.15989715e-01, 8.56544943e-01, 9.32168313e-02, 4.80172839e-01,
         7.09169621e-01, 9.36606087e-01]],

       [[2.76103207e-01, 4.18158355e-01, 5.94907217e-01, 5.97652318e-01,
         2.41601355e-01, 2.50203718e-01],
        [6.52009224e-01, 9.48094092e-01, 9.71853339e-02, 1.47501547e-01,
         8.29094885e-01, 9.93980686e-01]]])

In [111]:
np.delete(data, 0, axis=1)

array([[[0.71598971, 0.85654494, 0.09321683, 0.48017284, 0.70916962,
         0.93660609]],

       [[0.65200922, 0.94809409, 0.09718533, 0.14750155, 0.82909488,
         0.99398069]]])

In [113]:
np.save('new array', data)

In [ ]:
test = np.load('new arr